export const SET_IS_DEBUG = 'SET_IS_DEBUG';
export const SET_APP_START_TIME = 'SET_APP_START_TIME';
export const SET_INFO = 'SET_INFO';
export const SET_IS_HEADER_FOCUSED = 'SET_IS_HEADER_FOCUSED';
export const SET_NEXT_URL = 'SET_NEXT_URL';
export const SET_SCREEN = 'SET_SCREEN';
export const SET_IS_RETURNING_FROM_PLAYER = 'SET_IS_RETURNING_FROM_PLAYER';
export const SET_PLAYER = 'SET_PLAYER';
export const SET_IS_APP_LOADED = 'SET_IS_APP_LOADED';
export const SET_IS_FEED_READY = 'SET_IS_FEED_READY';
export const SET_PLAYLISTS = 'SET_PLAYLISTS';
export const SET_POSITION = 'SET_POSITION';
export const SET_DEFAULT_STATE = 'SET_DEFAULT_STATE';
export const SET_SHOULD_RETRY_BE_FOCUSED = 'SET_SHOULD_RETRY_BE_FOCUSED';
export const SET_SHOULD_SERMONS_BE_FOCUSED = 'SET_SHOULD_SERMONS_BE_FOCUSED';
export const SET_SHOULD_SEARCH_BE_FOCUSED = 'SET_SHOULD_SEARCH_BE_FOCUSED';
export const SET_SHOULD_WATCHLIVE_BE_FOCUSED =
  'SET_SHOULD_WATCHLIVE_BE_FOCUSED';
